name: 游냀 Snake Game Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"  # Gera uma vez por dia
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: 游닌 Checkout do reposit칩rio
        uses: actions/checkout@v3

      - name: 游냀 Gerar cobra comendo contribui칞칫es
        uses: Platane/snk@v3
        with:
          github_user_name: PauloHenriquebds
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg
          color_snake: "#800080"  # Cobra roxa

      - name: 游 Commit do SVG gerado
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Atualiza snake.svg automaticamente 游냀"
          add: "dist/*.svg"

      - name: 游댃 Push para o reposit칩rio
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Atualiza o Snake Game autom치tico
